/**
 * Tests for ai-gov upgrade command.
 * Verifies: hooks regenerated, steering preserved by default,
 * steering overwritten with --force, app name preserved from CLAUDE.md,
 * dry-run writes nothing, cross-platform chmod safety.
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { runUpgrade } from '../src/commands/upgrade.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTmpDir(prefix: string): string {
    const dir = join(tmpdir(), `ai-gov-upgrade-${prefix}-${Date.now()}`);
    mkdirSync(dir, { recursive: true });
    return dir;
}

/**
 * Creates a minimal project that looks like it was previously initialised by
 * ai-gov init — has .claude/ with hooks/, git-hooks/, commands/, steering/.
 */
function makeInitialisedProject(dir: string, appName = 'MyExistingApp'): void {
    writeFileSync(join(dir, 'package.json'), JSON.stringify({
        name: 'test-app',
        version: '1.0.0',
        dependencies: { react: '^18.0.0' },
    }, null, 2));

    const claudeDir = join(dir, '.claude');
    mkdirSync(join(claudeDir, 'hooks'),     { recursive: true });
    mkdirSync(join(claudeDir, 'commands'),  { recursive: true });
    mkdirSync(join(claudeDir, 'git-hooks'), { recursive: true });
    mkdirSync(join(claudeDir, 'steering'),  { recursive: true });

    // CLAUDE.md with embedded app name (format generated by ai-gov)
    writeFileSync(join(claudeDir, 'CLAUDE.md'),
        `# AI Governance\n\n**App:** ${appName} — A test application\n\n## Rules\n`);

    // Old / placeholder hook files (upgrade should replace these)
    writeFileSync(join(claudeDir, 'hooks', 'check-secrets.sh'),
        '#!/bin/bash\n# PLACEHOLDER OLD VERSION\nexit 0\n');
    writeFileSync(join(claudeDir, 'hooks', 'protect-files.sh'),
        '#!/bin/bash\n# PLACEHOLDER OLD VERSION\nexit 0\n');

    // Steering files with team-specific content (upgrade must NOT touch these by default)
    writeFileSync(join(claudeDir, 'steering', 'architecture.md'),
        '# Team Architecture\nCustom content — DO NOT OVERWRITE.\n');
    writeFileSync(join(claudeDir, 'steering', 'coding-standards.md'),
        '# Team Standards\nCustom standards — DO NOT OVERWRITE.\n');
    writeFileSync(join(claudeDir, 'steering', 'workflow.md'),
        '# Team Workflow\nCustom workflow — DO NOT OVERWRITE.\n');
    writeFileSync(join(claudeDir, 'steering', 'constitution.md'),
        '# Team Constitution\nCustom constitution — DO NOT OVERWRITE.\n');
}

// ---------------------------------------------------------------------------
// Suite: hook regeneration
// ---------------------------------------------------------------------------

describe('upgrade — hook regeneration', () => {
    let projectDir: string;

    beforeAll(() => {
        projectDir = makeTmpDir('hooks');
        makeInitialisedProject(projectDir);
        runUpgrade({ dir: projectDir, force: false, dryRun: false });
    });

    test('replaces stale Claude Code hooks', () => {
        const secretsHook = readFileSync(
            join(projectDir, '.claude', 'hooks', 'check-secrets.sh'), 'utf-8',
        );
        // Old placeholder content must be gone; real hook content present
        expect(secretsHook).not.toContain('PLACEHOLDER OLD VERSION');
        expect(secretsHook).toContain('#!/usr/bin/env bash');
    });

    test('generates all expected hook files', () => {
        const hooks = [
            'check-secrets.sh', 'protect-files.sh', 'block-dangerous-commands.sh',
            'check-spec-exists.sh', 'session-continuity.sh', 'format-code.sh',
            'analyze-code.sh', 'check-feature-readme.sh', 'check-consistency.sh',
            'check-file-size.sh', 'post-task-checklist.sh',
        ];
        for (const h of hooks) {
            expect(existsSync(join(projectDir, '.claude', 'hooks', h))).toBe(true);
        }
    });

    test('regenerates git-hook scripts', () => {
        expect(existsSync(join(projectDir, '.claude', 'git-hooks', 'pre-commit.sh'))).toBe(true);
        expect(existsSync(join(projectDir, '.claude', 'git-hooks', 'checks', 'secrets.sh'))).toBe(true);
        expect(existsSync(join(projectDir, '.claude', 'git-hooks', 'checks', 'file-size.sh'))).toBe(true);
    });

    test('regenerates slash commands', () => {
        const commands = ['audit.md', 'new-feature.md', 'edit-feature.md', 'fix.md',
            'refactor.md', 'hotfix.md', 'explore.md', 'jira.md', 'backlog.md'];
        for (const c of commands) {
            expect(existsSync(join(projectDir, '.claude', 'commands', c))).toBe(true);
        }
    });

    test('regenerates .claude/CLAUDE.md', () => {
        const content = readFileSync(join(projectDir, '.claude', 'CLAUDE.md'), 'utf-8');
        expect(content.length).toBeGreaterThan(100);
        expect(content).toContain('##'); // has sections
    });

    test('jira.md command generated on upgrade', () => {
        expect(existsSync(join(projectDir, '.claude', 'commands', 'jira.md'))).toBe(true);
        const content = readFileSync(join(projectDir, '.claude', 'commands', 'jira.md'), 'utf-8');
        expect(content.startsWith('# /jira')).toBe(true);
        expect(content).toContain('jira_get');
    });

    test('generated hooks use python3/jq dual runtime (no jq-only guard)', () => {
        const hook = readFileSync(join(projectDir, '.claude', 'hooks', 'check-secrets.sh'), 'utf-8');
        expect(hook).not.toContain('command -v jq &>/dev/null || exit 0');
        expect(hook).toContain('python3');
    });
});

// ---------------------------------------------------------------------------
// Suite: steering file preservation
// ---------------------------------------------------------------------------

describe('upgrade — steering preservation', () => {
    let projectDir: string;

    beforeAll(() => {
        projectDir = makeTmpDir('steering');
        makeInitialisedProject(projectDir);
        runUpgrade({ dir: projectDir, force: false, dryRun: false });
    });

    test('preserves architecture.md team content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'architecture.md'), 'utf-8',
        );
        expect(content).toContain('DO NOT OVERWRITE');
    });

    test('preserves coding-standards.md team content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'coding-standards.md'), 'utf-8',
        );
        expect(content).toContain('DO NOT OVERWRITE');
    });

    test('preserves workflow.md team content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'workflow.md'), 'utf-8',
        );
        expect(content).toContain('DO NOT OVERWRITE');
    });

    test('preserves constitution.md team content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'constitution.md'), 'utf-8',
        );
        expect(content).toContain('DO NOT OVERWRITE');
    });
});

// ---------------------------------------------------------------------------
// Suite: --force overwrites steering
// ---------------------------------------------------------------------------

describe('upgrade --force — steering overwrite', () => {
    let projectDir: string;

    beforeAll(() => {
        projectDir = makeTmpDir('force');
        makeInitialisedProject(projectDir);
        runUpgrade({ dir: projectDir, force: true, dryRun: false });
    });

    test('overwrites architecture.md with generated content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'architecture.md'), 'utf-8',
        );
        // Generated content replaces the placeholder
        expect(content).not.toContain('DO NOT OVERWRITE');
        expect(content.length).toBeGreaterThan(50);
    });

    test('overwrites coding-standards.md with generated content', () => {
        const content = readFileSync(
            join(projectDir, '.claude', 'steering', 'coding-standards.md'), 'utf-8',
        );
        expect(content).not.toContain('DO NOT OVERWRITE');
    });

    test('generates task-estimates.md in steering under --force', () => {
        expect(existsSync(join(projectDir, '.claude', 'steering', 'task-estimates.md'))).toBe(true);
        const content = readFileSync(join(projectDir, '.claude', 'steering', 'task-estimates.md'), 'utf-8');
        expect(content).toContain('[~');
        expect(content).toContain('[S]');
    });
});

// ---------------------------------------------------------------------------
// Suite: app name preserved from existing CLAUDE.md
// ---------------------------------------------------------------------------

describe('upgrade — app name preservation', () => {
    test('reads app name from existing .claude/CLAUDE.md', () => {
        const projectDir = makeTmpDir('appname');
        makeInitialisedProject(projectDir, 'AcmePaymentService');
        runUpgrade({ dir: projectDir, force: false, dryRun: false });

        const newClaudeMd = readFileSync(join(projectDir, '.claude', 'CLAUDE.md'), 'utf-8');
        expect(newClaudeMd).toContain('AcmePaymentService');
    });

    test('falls back to package.json name when CLAUDE.md has no app name', () => {
        const projectDir = makeTmpDir('pkgname');
        writeFileSync(join(projectDir, 'package.json'), JSON.stringify({
            name: 'my-pkg-app', version: '1.0.0',
        }, null, 2));
        const claudeDir = join(projectDir, '.claude');
        mkdirSync(join(claudeDir, 'hooks'),     { recursive: true });
        mkdirSync(join(claudeDir, 'commands'),  { recursive: true });
        mkdirSync(join(claudeDir, 'git-hooks'), { recursive: true });
        mkdirSync(join(claudeDir, 'steering'),  { recursive: true });
        // CLAUDE.md with no **App:** line
        writeFileSync(join(claudeDir, 'CLAUDE.md'), '# Governance\nNo app name here.\n');

        runUpgrade({ dir: projectDir, force: false, dryRun: false });

        const newClaudeMd = readFileSync(join(claudeDir, 'CLAUDE.md'), 'utf-8');
        expect(newClaudeMd).toContain('my-pkg-app');
    });
});

// ---------------------------------------------------------------------------
// Suite: dry-run
// ---------------------------------------------------------------------------

describe('upgrade --dry-run', () => {
    test('does not modify hook files', () => {
        const projectDir = makeTmpDir('dryrun');
        makeInitialisedProject(projectDir);

        const sentinel = '#!/bin/bash\n# SENTINEL — must not change\nexit 0\n';
        writeFileSync(join(projectDir, '.claude', 'hooks', 'check-secrets.sh'), sentinel);

        runUpgrade({ dir: projectDir, force: false, dryRun: true });

        const content = readFileSync(
            join(projectDir, '.claude', 'hooks', 'check-secrets.sh'), 'utf-8',
        );
        expect(content).toBe(sentinel);
    });

    test('does not create new git-hook files', () => {
        const projectDir = makeTmpDir('dryrun2');
        makeInitialisedProject(projectDir);

        // Ensure no git-hooks exist initially beyond the empty dir
        const preCommit = join(projectDir, '.claude', 'git-hooks', 'pre-commit.sh');
        expect(existsSync(preCommit)).toBe(false);

        runUpgrade({ dir: projectDir, force: false, dryRun: true });

        expect(existsSync(preCommit)).toBe(false);
    });
});
