export function generateArchitectureCheck(): string {
    return `#!/usr/bin/env bash
# Architecture compliance check (BLOCKING)
# Rules are read from .claude/steering/architecture.md (## Hook Data section).
# If no arch-layer lines are present in that file, the check exits silently.
#
# Steering format (generated by ai-gov, editable by /audit):
#   arch-layer: <name> | paths: <dir1>/, <dir2>/
#   arch-rule:  <layerA> | cannot-import | <layerB> | <hint>
#   arch-rule:  <layer>  | no-network    | <hint>
#   arch-rule:  <layer>  | no-framework  | <hint>

HOOKS_DIR="$1"
AGENT_DIR=$(dirname "$HOOKS_DIR")
STEERING_DIR="$AGENT_DIR/steering"
CONFIG_FILE="$HOOKS_DIR/config.json"
ARCH_MD="$STEERING_DIR/architecture.md"

# No steering directory — skip silently
[[ ! -d "$STEERING_DIR" ]] && exit 0

# No architecture.md — skip silently
[[ ! -f "$ARCH_MD" ]] && exit 0

# No arch-layer definitions — not configured for this project, skip silently
grep -qi '^arch-layer:' "$ARCH_MD" || exit 0

# --- Parse legacy exclusions from steering docs ---
LEGACY_PATTERNS=""
for f in "$STEERING_DIR"/*.md; do
    [[ ! -f "$f" ]] && continue
    while IFS= read -r line; do
        cleaned=$(echo "$line" | sed -E 's/^[[:space:]#*-]*//' | grep -i '^legacy' | sed -E 's/^legacy[[:space:]]*:[[:space:]]*//')
        if [[ -n "$cleaned" ]]; then
            IFS=',' read -ra parts <<< "$cleaned"
            for p in "\${parts[@]}"; do
                trimmed=$(echo "$p" | xargs)
                [[ -n "$trimmed" ]] && LEGACY_PATTERNS="$LEGACY_PATTERNS|$trimmed"
            done
        fi
    done < "$f"
done
LEGACY_PATTERNS="\${LEGACY_PATTERNS#|}"

# --- Read exclude-patterns from config.json ---
EXCLUDE_PATTERNS=""
if [[ -f "$CONFIG_FILE" ]]; then
    if command -v jq &>/dev/null; then
        while IFS= read -r pattern; do
            [[ -n "$pattern" ]] && EXCLUDE_PATTERNS="$EXCLUDE_PATTERNS|$pattern"
        done < <(jq -r '."pre-commit".architecture."exclude-patterns"[]? // empty' "$CONFIG_FILE" 2>/dev/null)
    elif command -v python3 &>/dev/null; then
        while IFS= read -r pattern; do
            [[ -n "$pattern" ]] && EXCLUDE_PATTERNS="$EXCLUDE_PATTERNS|$pattern"
        done < <(python3 -c "
import json,sys
try:
    with open(sys.argv[1]) as f: c=json.load(f)
    for p in c.get('pre-commit',{}).get('architecture',{}).get('exclude-patterns',[]): print(p)
except: pass
" "$CONFIG_FILE" 2>/dev/null)
    fi
    EXCLUDE_PATTERNS="\${EXCLUDE_PATTERNS#|}"
fi

# --- Helpers ---

# Return the path regex for a named layer from architecture.md
# Example: get_layer_regex "ui" → "presentation/|screens/|widgets/"
get_layer_regex() {
    local name="$1"
    grep -iE "^arch-layer:[[:space:]]*\${name}[[:space:]]*\\|" "$ARCH_MD" 2>/dev/null | head -1 | \
        grep -oiE 'paths:[^$]*' | \
        sed -E 's/paths:[[:space:]]*//' | \
        sed 's/,[[:space:]]*/|/g' | \
        tr -d ' '
}

# Convert path regex "presentation/|screens/" to import regex with word boundaries.
# Produces [./]segment[./] — matches .ui. (Kotlin/Java dot imports) and /ui/ (JS/Dart/Python
# slash imports) but not substrings like uuid, guide, fastapi, or ModelMapper.
paths_to_import_regex() {
    echo "$1" | tr '|' '\\n' | sed 's|/$||' | \\
        sed 's|.*|[./]&[./]|' | paste -sd '|' - 2>/dev/null || echo "$1"
}

# --- Main violation scan ---
TMPFILE=$(mktemp)

while IFS= read -r file; do
    [[ -z "$file" ]] && continue
    [[ ! -f "$file" ]] && continue

    # Skip non-code files
    case "$file" in
        *.md|*.txt|*.json|*.yaml|*.yml|*.xml|*.gradle|*.properties|*.lock) continue ;;
    esac

    # Skip test files
    bn=$(basename "$file")
    echo "$bn" | grep -qE '\\.(test|spec)\\.|_test\\.|Test\\.' && continue

    # Skip legacy files
    if [[ -n "$LEGACY_PATTERNS" ]]; then
        echo "$file" | grep -qE "$LEGACY_PATTERNS" && continue
    fi

    # Skip config-defined exclude-patterns
    if [[ -n "$EXCLUDE_PATTERNS" ]]; then
        echo "$file" | grep -qE "$EXCLUDE_PATTERNS" && continue
    fi

    CONTENT=$(git show ":0:$file" 2>/dev/null) || continue

    # Process each arch-rule line
    while IFS= read -r rule_line; do
        rule=$(echo "$rule_line" | sed -E 's/^arch-rule:[[:space:]]*//')
        layerA=$(echo "$rule" | cut -d'|' -f1 | xargs | tr '[:upper:]' '[:lower:]')
        ruleType=$(echo "$rule" | cut -d'|' -f2 | xargs | tr -d ' ')

        layerA_regex=$(get_layer_regex "$layerA")
        [[ -z "$layerA_regex" ]] && continue

        echo "$file" | grep -qiE "($layerA_regex)" || continue

        case "$ruleType" in
            cannot-import)
                layerB=$(echo "$rule" | cut -d'|' -f3 | xargs | tr '[:upper:]' '[:lower:]')
                hint=$(echo "$rule" | cut -d'|' -f4 | xargs)
                layerB_regex=$(get_layer_regex "$layerB")
                [[ -z "$layerB_regex" ]] && continue
                import_regex=$(paths_to_import_regex "$layerB_regex")
                if echo "$CONTENT" | grep -qiE "(import|from).*($import_regex)"; then
                    {
                        echo "  ❌ ARCHITECTURE: $file"
                        echo "     → $layerA layer must not import $layerB layer"
                        [[ -n "$hint" ]] && echo "     → $hint"
                    } >> "$TMPFILE"
                fi
                ;;

            no-network)
                hint=$(echo "$rule" | cut -d'|' -f3 | xargs)
                NETWORK_PAT="Retrofit|HttpClient|fetch\\(|axios\\.|dio\\.|HttpURLConnection|OkHttp|Volley|URLSession|Ktor|XMLHttpRequest"
                if echo "$CONTENT" | grep -qiE "($NETWORK_PAT)"; then
                    {
                        echo "  ❌ ARCHITECTURE: $file"
                        echo "     → $layerA layer must not make direct network calls"
                        [[ -n "$hint" ]] && echo "     → $hint"
                    } >> "$TMPFILE"
                fi
                ;;

            no-framework)
                hint=$(echo "$rule" | cut -d'|' -f3 | xargs)
                FW_PAT="import.*(android|androidx|flutter|react|angular|javax\\.servlet)"
                if echo "$CONTENT" | grep -qiE "$FW_PAT"; then
                    {
                        echo "  ❌ ARCHITECTURE: $file"
                        echo "     → $layerA layer must remain framework-agnostic"
                        [[ -n "$hint" ]] && echo "     → $hint"
                    } >> "$TMPFILE"
                fi
                ;;
        esac

    done < <(grep -i '^arch-rule:' "$ARCH_MD" 2>/dev/null)

done

if [[ -s "$TMPFILE" ]]; then
    cat "$TMPFILE"
    echo ""
    echo "     ℹ️  Legacy modules are excluded from this check."
    echo "     ℹ️  Mark paths as legacy in steering docs to exclude them."
    rm -f "$TMPFILE"
    exit 1
fi

rm -f "$TMPFILE"
exit 0
`;
}
