export function generateKnowledgeConfirmedCheck(): string {
    return `#!/usr/bin/env bash
# Generated by ai-gov — do not edit manually
# Blocks removal of [CONFIRMED] entries from knowledge/*.md files
# Bypass: AI_GOV_KNOWLEDGE_OVERRIDE=1 git commit -m '<message>'
#
# Note: the pre-commit hook runs BEFORE git writes the commit message,
# so a "Knowledge-override:" trailer cannot be detected here. The env-var
# bypass is the only reliable mechanism at pre-commit time.

set -euo pipefail

# Env-var bypass — accepts "1" or "true" (case-insensitive)
case "\${AI_GOV_KNOWLEDGE_OVERRIDE:-}" in
    1|true|TRUE|True) exit 0 ;;
esac

STAGED_FILES=$(cat)
KNOWLEDGE_FILES=$(echo "$STAGED_FILES" | grep '^knowledge/.*\\.md$' || true)

[[ -z "$KNOWLEDGE_FILES" ]] && exit 0

BLOCKED=0
DETAILS=""

while IFS= read -r file; do
    [[ -z "$file" ]] && continue

    # If file has no HEAD version, it's new — allow
    if ! git cat-file -e "HEAD:$file" 2>/dev/null; then
        continue
    fi

    # Extract [CONFIRMED] lines from HEAD version
    HEAD_CONFIRMED=$(git show "HEAD:$file" 2>/dev/null | grep -F '[CONFIRMED]' || true)

    # Extract [CONFIRMED] lines from staged version
    STAGED_CONFIRMED=$(git show ":$file" 2>/dev/null | grep -F '[CONFIRMED]' || true)

    # Check each HEAD [CONFIRMED] line is still present in staged
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        if ! echo "$STAGED_CONFIRMED" | grep -qF "$line"; then
            BLOCKED=$((BLOCKED + 1))
            DETAILS="$DETAILS\\n    ✗ $file: removed — $line"
        fi
    done <<< "$HEAD_CONFIRMED"

done <<< "$KNOWLEDGE_FILES"

if [[ $BLOCKED -gt 0 ]]; then
    echo ""
    echo "  ⛔ Knowledge guard: $BLOCKED [CONFIRMED] entry/entries removed"
    echo -e "$DETAILS"
    echo ""
    echo "  [CONFIRMED] entries are human-verified — removal requires explicit override."
    echo "  To bypass: AI_GOV_KNOWLEDGE_OVERRIDE=1 git commit -m 'your message'"
    echo ""
fi

exit 0
`;
}
