/**
 * Shared HTML scaffold for knowledge export files.
 * Used by tech-knowledge and product-knowledge commands to avoid
 * duplicating ~80 lines of identical CSS + page wrapper.
 */

export const KNOWLEDGE_HTML_CSS = `    *, *::before, *::after { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1.5rem; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 1.6rem; border-bottom: 2px solid #e5e7eb; padding-bottom: .5rem; }
    h2 { font-size: 1.2rem; margin-top: 2rem; color: #374151; }
    h3 { font-size: 1rem; margin-top: 1.5rem; color: #4b5563; }
    .meta { background: #fefce8; border-left: 4px solid #eab308; padding: .75rem 1rem; border-radius: 4px; font-size: .875rem; margin-bottom: 1.5rem; }
    .drift { background: #fef2f2; border-left: 4px solid #dc2626; padding: .75rem 1rem; border-radius: 4px; font-size: .875rem; margin: 1rem 0; }
    .tag-inferred { color: #6b7280; font-size: .75rem; font-weight: 600; }
    .tag-confirmed { color: #16a34a; font-size: .75rem; font-weight: 600; }
    .tag-unknown { color: #dc2626; font-size: .75rem; font-weight: 600; }
    table { width: 100%; border-collapse: collapse; font-size: .9rem; margin: 1rem 0; }
    th { background: #f3f4f6; text-align: left; padding: .5rem .75rem; border: 1px solid #e5e7eb; }
    td { padding: .5rem .75rem; border: 1px solid #e5e7eb; vertical-align: top; }
    tr:nth-child(even) td { background: #f9fafb; }
    ol, ul { padding-left: 1.25rem; }
    li { margin: .25rem 0; }
    .mermaid { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 1rem; margin: 1rem 0; }
    .layer-map { font-family: monospace; background: #f3f4f6; padding: 1rem; border-radius: 6px; font-size: .875rem; line-height: 1.8; }
    .flow-entry { font-size: .85rem; color: #6b7280; margin-top: .25rem; }
    dl { display: grid; grid-template-columns: max-content 1fr; gap: .25rem .75rem; font-size: .9rem; margin: .5rem 0; }
    dt { font-weight: 600; color: #374151; }
    dd { margin: 0; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; font-size: .8rem; color: #9ca3af; }`;

export interface KnowledgePageOptions {
    title: string;
    stackDisplay: string;
    bodyHtml: string;
    generatedByCommand: string;
}

export function wrapKnowledgePage(opts: KnowledgePageOptions): string {
    const { title, stackDisplay, bodyHtml, generatedByCommand } = opts;
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} | ${stackDisplay}</title>
  <!-- Mermaid loaded from CDN — requires internet to render diagrams -->
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
${KNOWLEDGE_HTML_CSS}
  </style>
</head>
<body>
  <h1>${title} <span style="color:#6b7280;font-size:.9rem">| ${stackDisplay}</span></h1>
  <div class="meta">
    ⚠ Auto-generated [INFERRED]. Manual edits to [CONFIRMED] entries are preserved on re-run.<br>
    Generated: [today's date] (git: [GIT_HASH])
  </div>

${bodyHtml}

  <footer>Generated by ${generatedByCommand} · ${stackDisplay} · git: [GIT_HASH]</footer>

  <script>mermaid.initialize({ startOnLoad: true, theme: 'neutral' });</script>
</body>
</html>`;
}
