import type { GovernanceConfig } from '../../../types.js';

export function generateHooksReadme(c: GovernanceConfig): string {
  return `# Kiro Hooks — ${c.project.appName}

> Generated by ai-gov v${c.hookVersion}. These .kiro.hook files are read by Kiro automatically.

## Hook Files

| File | Event | Action | Purpose |
|------|-------|--------|---------|
| \`block-dangerous-commands.kiro.hook\` | preToolUse (shell) | askAgent | Blocks force push, destructive git ops |
| \`protect-files.kiro.hook\` | preToolUse (write) | askAgent | Warns on high-risk file edits |
| \`pre-write-secrets-gate.kiro.hook\` | preToolUse (write) | askAgent | Blocks writes containing hardcoded credentials |
${c.specFirstEnabled ? '| `spec-first-gate.kiro.hook` | preToolUse (write) | askAgent | Blocks writes without spec |\n' : ''}| \`check-secrets.kiro.hook\` | fileEdited | askAgent | Scans for hardcoded credentials (post-hoc) |
| \`format-code.kiro.hook\` | postToolUse (write) | runCommand | Auto-formats after write |
| \`analyze-code.kiro.hook\` | postTaskExecution | runCommand | Runs linter once per task completion |
| \`session-continuity.kiro.hook\` | promptSubmit | askAgent | Context preservation |
| \`post-task-checklist.kiro.hook\` | postTaskExecution | askAgent | Post-task verification |

## How Kiro Hooks Work

- **preToolUse** hooks fire before a tool executes. If the hook responds with "DENIED", the tool call is blocked.
- **postToolUse** hooks fire after a tool executes. They can run commands or prompt the agent.
- **fileEdited** hooks fire when a file is saved. Used for post-hoc checks like credential scanning.
- **promptSubmit** hooks fire when a message is sent. Used for session context and task classification.
- **postTaskExecution** hooks fire after a spec task is completed. Used for verification checklists.

## Workflow Shortcuts (userTriggered)

These hooks appear as buttons in the Kiro hooks panel. Click to trigger a guided workflow — the Kiro equivalent of Claude Code's slash commands.

| File | Workflow | What It Does |
|------|----------|--------------|
| \`workflow-audit.kiro.hook\` | Audit | Full governance audit: observe codebase, compare to steering, find drift and dead code |
| \`workflow-new-feature.kiro.hook\` | New Feature | Spec-first 3-gate workflow: requirements → design → tasks → implement |
| \`workflow-fix.kiro.hook\` | Fix | Bug diagnosis: reproduce → root cause → minimal fix → regression test |
| \`workflow-refactor.kiro.hook\` | Refactor | Plan-first refactor: impact analysis gate → tests before → apply → tests after |
| \`workflow-hotfix.kiro.hook\` | Hotfix | Emergency production fix: smallest change, must have test, safe to deploy |
| \`workflow-explore.kiro.hook\` | Explore | Read-only codebase exploration: trace data flows, map dependencies |
| \`workflow-edit-feature.kiro.hook\` | Edit Feature | Add to or change an existing feature: update spec gates, preserve done tasks, implement only new tasks |

### How to use

1. Open the **Agent Hooks** panel in Kiro
2. Find the workflow hook (e.g. "New Feature")
3. Click the trigger button
4. The agent will ask what you need and guide you through the workflow

These are equivalent to Claude Code's \`/audit\`, \`/new-feature\`, \`/fix\`, \`/refactor\`, \`/hotfix\`, \`/explore\`, and \`/edit-feature\` commands.

## Customization

Add your own hooks as .kiro.hook files in this directory. Each file must follow the schema:

\`\`\`json
{
  "name": "My Custom Hook",
  "version": "1.0.0",
  "when": { "type": "preToolUse", "toolTypes": ["write"] },
  "then": { "type": "askAgent", "prompt": "Your prompt here" }
}
\`\`\`
`;
}
