#!/usr/bin/env bash
# Generated by ai-gov — validates conventional commit format
MSG_FILE="$1"
MSG=$(head -1 "$MSG_FILE")
DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config.json"

command -v jq &>/dev/null || exit 0

# Skip if disabled
enabled=$(jq -r '.["commit-msg"]["conventional-commits"] // true' "$CONFIG" 2>/dev/null)
[[ "$enabled" != "true" ]] && exit 0

# Skip merge commits
echo "$MSG" | grep -qE '^Merge ' && exit 0

# Skip revert commits
echo "$MSG" | grep -qE '^Revert ' && exit 0

# Skip fixup/squash (interactive rebase)
echo "$MSG" | grep -qE '^(fixup|squash)! ' && exit 0

# Skip during rebase
[[ -d ".git/rebase-merge" || -d ".git/rebase-apply" ]] && exit 0

# Read allowed types from config (fallback to defaults)
TYPES=$(jq -r '.["commit-msg"]["allowed-types"] // ["feat","fix","refactor","hotfix","docs","test","chore","style","perf","ci","build"] | join("|")' "$CONFIG" 2>/dev/null)
MIN_LEN=$(jq -r '.["commit-msg"]["min-description-length"] // 10' "$CONFIG" 2>/dev/null)

# Validate format: type(scope): description
if ! echo "$MSG" | grep -qE "^($TYPES)(\([a-zA-Z0-9_-]+\))?: .{${MIN_LEN},}"; then
    echo ""
    echo "  ❌ COMMIT MESSAGE: doesn't follow conventional format"
    echo ""
    echo "  Expected: <type>(<scope>): <description>"
    echo "  Types:    $TYPES"
    echo "  Minimum:  $MIN_LEN characters in description"
    echo ""
    echo "  Examples:"
    echo "    feat: add user profile edit screen"
    echo "    fix(auth): resolve null pointer in login flow"
    echo "    refactor: extract auth logic into usecase layer"
    echo ""
    echo "  Your message: \"$MSG\""
    echo ""
    exit 1
fi

# Check ticket reference if required
REQ_TICKET=$(jq -r '.["commit-msg"]["require-ticket-ref"] // false' "$CONFIG" 2>/dev/null)
if [[ "$REQ_TICKET" == "true" ]]; then
    TICKET_PAT=$(jq -r '.["commit-msg"]["ticket-pattern"] // "[A-Z]+-[0-9]+"' "$CONFIG" 2>/dev/null)
    FULL_MSG=$(cat "$MSG_FILE")
    if ! echo "$FULL_MSG" | grep -qE "$TICKET_PAT"; then
        echo ""
        echo "  ❌ COMMIT MESSAGE: ticket reference required but not found"
        echo "  Pattern: $TICKET_PAT (e.g., TICKET-123)"
        echo ""
        exit 1
    fi
fi

exit 0
