#!/usr/bin/env bash
# Generated by ai-gov — do not edit manually
# Runs enabled checks from .claude/git-hooks/checks/

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config.json"

# Require jq for config parsing
command -v jq &>/dev/null || { echo "  ⚠️  jq not installed — git hooks need jq. Skipping checks."; exit 0; }

# Skip during merge
[[ -f ".git/MERGE_HEAD" ]] && exit 0

# Skip during rebase
[[ -d ".git/rebase-merge" || -d ".git/rebase-apply" ]] && exit 0

# Get staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
[[ -z "$STAGED" ]] && exit 0

# Read config
cfg() { jq -r "$1" "$CONFIG" 2>/dev/null; }

ERRORS=0
WARNINGS=0

# Run each enabled check
run_check() {
    local name="$1" script="$2" mode="$3"
    local enabled
    enabled=$(cfg '."pre-commit"."'"$name"'".enabled // true')
    [[ "$enabled" != "true" ]] && return 0

    local output
    output=$(echo "$STAGED" | bash "$DIR/checks/$script" "$DIR" 2>&1) || true

    if [[ -n "$output" ]]; then
        echo "$output"
        if [[ "$mode" == "block" ]]; then
            ERRORS=$((ERRORS + 1))
        else
            WARNINGS=$((WARNINGS + 1))
        fi
    fi
}

echo ""
echo "  🔒 Pre-commit governance check"
echo "  ───────────────────────────────"

run_check "file-size"     "file-size.sh"     "block"
run_check "secrets"       "secrets.sh"        "block"
run_check "no-todos"      "no-todos.sh"       "warn"
run_check "no-debug"      "no-debug.sh"       "warn"

# These are off by default — team enables in config.json
run_check "format-check"  "format-check.sh"   "warn"
run_check "lint-check"    "lint-check.sh"      "warn"

echo ""
if [[ $ERRORS -gt 0 ]]; then
    echo "  ❌ $ERRORS blocking issue(s) found. Fix and try again."
    echo "  (bypass with: git commit --no-verify)"
    exit 1
elif [[ $WARNINGS -gt 0 ]]; then
    echo "  ⚠️  $WARNINGS warning(s). Commit allowed — consider fixing."
    exit 0
else
    echo "  ✅ All checks passed."
    exit 0
fi
