export function generatePreCommit(): string {
    return `#!/usr/bin/env bash
# Generated by ai-gov — do not edit manually
# Runs enabled checks from <agentDir>/git-hooks/checks/

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config.json"

# Skip during merge
[[ -f ".git/MERGE_HEAD" ]] && exit 0

# Skip during rebase
[[ -d ".git/rebase-merge" || -d ".git/rebase-apply" ]] && exit 0

# Get staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
[[ -z "$STAGED" ]] && exit 0

# Config reader — uses jq if available, falls back to python3, defaults to 'true' (enabled)
cfg() {
    local expr="$1"
    if command -v jq &>/dev/null; then
        jq -r "\${expr}" "$CONFIG" 2>/dev/null || echo "true"
    elif command -v python3 &>/dev/null; then
        python3 -c "
import json,sys,re
try:
    with open(sys.argv[1]) as f:
        c=json.load(f)
    keys=re.findall(r'[a-zA-Z0-9_-]+', sys.argv[2].split('//')[0])
    v=c
    for k in keys:
        v=v.get(k) if isinstance(v,dict) else None
    print('true' if v is True else ('false' if v is False else (str(v) if v is not None else 'true')))
except: print('true')
" "$CONFIG" "$expr" 2>/dev/null || echo "true"
    else
        echo "true"
    fi
}

ERRORS=0
WARNINGS=0

# Run each enabled check
run_check() {
    local name="$1" script="$2" mode="$3"
    local enabled
    enabled=$(cfg '."pre-commit"."'"$name"'".enabled // true')
    [[ "$enabled" != "true" ]] && return 0

    local output
    output=$(echo "$STAGED" | bash "$DIR/checks/$script" "$DIR" 2>&1) || true

    if [[ -n "$output" ]]; then
        echo "$output"
        if [[ "$mode" == "block" ]]; then
            ERRORS=$((ERRORS + 1))
        else
            WARNINGS=$((WARNINGS + 1))
        fi
    fi
}

echo ""
echo "  🔒 Pre-commit governance check"
echo "  ───────────────────────────────"

run_check "file-size"     "file-size.sh"     "warn"
run_check "secrets"       "secrets.sh"        "block"
run_check "no-todos"      "no-todos.sh"       "warn"
run_check "no-debug"      "no-debug.sh"       "warn"
run_check "architecture"  "architecture.sh"   "block"

# These are off by default — team enables in config.json
run_check "format-check"  "format-check.sh"   "warn"
run_check "lint-check"    "lint-check.sh"      "warn"

echo ""
if [[ $ERRORS -gt 0 ]]; then
    echo "  ❌ $ERRORS blocking issue(s) found. Fix and try again."
    echo "  (bypass with: git commit --no-verify)"
    exit 1
elif [[ $WARNINGS -gt 0 ]]; then
    echo "  ⚠️  $WARNINGS warning(s). Commit allowed — consider fixing."
    exit 0
else
    echo "  ✅ All checks passed."
    exit 0
fi
`;
}
