export function generatePreCommit(): string {
    return `#!/usr/bin/env bash
# Generated by ai-gov — do not edit manually
# Runs enabled checks from <agentDir>/git-hooks/checks/

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config.json"

# Skip during merge
[[ -f ".git/MERGE_HEAD" ]] && exit 0

# Skip during rebase
[[ -d ".git/rebase-merge" || -d ".git/rebase-apply" ]] && exit 0

# Get staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
[[ -z "$STAGED" ]] && exit 0

# Config reader — uses jq if available, falls back to python3, defaults to 'true' (enabled)
cfg() {
    local expr="$1"
    if command -v jq &>/dev/null; then
        jq -r "\${expr}" "$CONFIG" 2>/dev/null || echo "true"
    elif command -v python3 &>/dev/null; then
        python3 -c "
import json,sys,re
try:
    with open(sys.argv[1]) as f:
        c=json.load(f)
    keys=re.findall(r'[a-zA-Z0-9_-]+', sys.argv[2].split('//')[0])
    v=c
    for k in keys:
        v=v.get(k) if isinstance(v,dict) else None
    print('true' if v is True else ('false' if v is False else (str(v) if v is not None else 'true')))
except: print('true')
" "$CONFIG" "$expr" 2>/dev/null || echo "true"
    else
        echo "true"
    fi
}

ERRORS=0
WARNINGS=0

# Run each enabled check
run_check() {
    local name="$1" script="$2" mode="$3"
    local enabled
    enabled=$(cfg '."pre-commit"."'"$name"'".enabled // true')
    [[ "$enabled" != "true" ]] && return 0

    local output
    output=$(echo "$STAGED" | bash "$DIR/checks/$script" "$DIR" 2>&1) || true

    if [[ -n "$output" ]]; then
        echo "$output"
        if [[ "$mode" == "block" ]]; then
            ERRORS=$((ERRORS + 1))
        else
            WARNINGS=$((WARNINGS + 1))
        fi
    fi
}

echo ""
echo "  🔒 Pre-commit governance check"
echo "  ───────────────────────────────"

run_check "file-size"     "file-size.sh"     "warn"
run_check "secrets"       "secrets.sh"        "block"
run_check "no-todos"      "no-todos.sh"       "warn"
run_check "no-debug"      "no-debug.sh"       "warn"
run_check "architecture"  "architecture.sh"   "block"

# These are off by default — team enables in config.json
run_check "format-check"  "format-check.sh"   "warn"
run_check "lint-check"    "lint-check.sh"      "warn"

echo ""

# --- Pre-commit logging (Requirements 9.1–9.6, 15.1–15.3) ---
# Create log directory if it does not exist
mkdir -p .ai-gov/usage-logs/ || true

_AIGOV_LOG=".ai-gov/usage-logs/precommit.log"
_AIGOV_TS=$(date +%s) || true

# --- AI platform detection (Requirements 15.1, 15.2, 15.3) ---
_AIGOV_PLATFORM="manual"
_AIGOV_COMMAND=""

# Detect Claude Code: check for .claude/ session artifacts
if [ -d ".claude" ] && [ -n "$(ls -A .claude/ 2>/dev/null)" ]; then
    _AIGOV_PLATFORM="claude-code"
    # Attempt to detect command from recent session metadata
    if [ -f ".claude/session.json" ]; then
        _AIGOV_COMMAND=$(cat .claude/session.json 2>/dev/null | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"command"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/' 2>/dev/null) || true
    fi
    # Fallback: detect from commit message context markers (AI workflow prefixes)
    if [ -z "\$_AIGOV_COMMAND" ]; then
        _AIGOV_MSG=$(git log --format=%s -1 HEAD 2>/dev/null) || true
        case "\$_AIGOV_MSG" in
            feat:*|feat\\(*) _AIGOV_COMMAND="new-feature" ;;
            fix:*|fix\\(*) _AIGOV_COMMAND="fix" ;;
            refactor:*|refactor\\(*) _AIGOV_COMMAND="refactor" ;;
            explore:*|explore\\(*) _AIGOV_COMMAND="explore" ;;
            hotfix:*|hotfix\\(*) _AIGOV_COMMAND="hotfix" ;;
        esac
    fi || true
# Detect Kiro: check for .kiro/ workspace markers
elif [ -d ".kiro" ] && [ -n "$(ls -A .kiro/ 2>/dev/null)" ]; then
    _AIGOV_PLATFORM="kiro"
    # Attempt to detect command from kiro session or workspace metadata
    if [ -f ".kiro/session.json" ]; then
        _AIGOV_COMMAND=$(cat .kiro/session.json 2>/dev/null | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"command"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/' 2>/dev/null) || true
    fi
    # Fallback: detect from commit message context markers
    if [ -z "\$_AIGOV_COMMAND" ]; then
        _AIGOV_MSG=$(git log --format=%s -1 HEAD 2>/dev/null) || true
        case "\$_AIGOV_MSG" in
            feat:*|feat\\(*) _AIGOV_COMMAND="new-feature" ;;
            fix:*|fix\\(*) _AIGOV_COMMAND="fix" ;;
            refactor:*|refactor\\(*) _AIGOV_COMMAND="refactor" ;;
            explore:*|explore\\(*) _AIGOV_COMMAND="explore" ;;
            hotfix:*|hotfix\\(*) _AIGOV_COMMAND="hotfix" ;;
        esac
    fi || true
fi || true
# --- End AI platform detection ---

if [[ $ERRORS -gt 0 ]]; then
    echo "\${_AIGOV_TS}|fail|\${_AIGOV_PLATFORM}|\${_AIGOV_COMMAND}" >> "\$_AIGOV_LOG" || true
else
    echo "\${_AIGOV_TS}|pass|\${_AIGOV_PLATFORM}|\${_AIGOV_COMMAND}" >> "\$_AIGOV_LOG" || true
fi

# Log rotation: keep most recent 500 entries if file exceeds 500 lines
_AIGOV_LINES=$(wc -l < "\$_AIGOV_LOG" 2>/dev/null) || true
_AIGOV_LINES=\${_AIGOV_LINES// /}
if [ "\${_AIGOV_LINES:-0}" -gt 500 ] 2>/dev/null; then
    tail -500 "\$_AIGOV_LOG" > "\$_AIGOV_LOG.tmp" && mv "\$_AIGOV_LOG.tmp" "\$_AIGOV_LOG" || true
fi
# --- End pre-commit logging and AI detection ---

if [[ $ERRORS -gt 0 ]]; then
    echo "  ❌ $ERRORS blocking issue(s) found. Fix and try again."
    echo "  (bypass with: git commit --no-verify)"
    exit 1
elif [[ $WARNINGS -gt 0 ]]; then
    echo "  ⚠️  $WARNINGS warning(s). Commit allowed — consider fixing."
    exit 0
else
    echo "  ✅ All checks passed."
    exit 0
fi
`;
}
