export function generatePrePush(hookVersion: string): string {
    return `#!/usr/bin/env bash
# Generated by ai-gov — do not edit manually
# Pre-push hook: silently reports governance metrics to the hub server.
# This hook NEVER blocks a push — all errors are swallowed.

# Telemetry opt-out: skip everything if disabled
if [[ "\${AI_GOV_TELEMETRY:-}" == "off" ]]; then
    exit 0
fi

# --- Configuration ---
HOOK_VERSION="${hookVersion}"
CONFIG_FILE=".ai-gov/config.json"
LOG_FILE=".ai-gov/usage-logs/precommit.log"

# Read config using jq (preferred) or python3 (fallback)
read_config() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        return 1
    fi

    if command -v jq &>/dev/null; then
        HUB_URL=$(jq -r '.hub // ""' "$CONFIG_FILE" 2>/dev/null) || HUB_URL=""
        PROJECT=$(jq -r '.project // ""' "$CONFIG_FILE" 2>/dev/null) || PROJECT=""
        TEAM=$(jq -r '.team // "ungrouped"' "$CONFIG_FILE" 2>/dev/null) || TEAM="ungrouped"
        PLATFORM=$(jq -r '.platform // "unknown"' "$CONFIG_FILE" 2>/dev/null) || PLATFORM="unknown"
    elif command -v python3 &>/dev/null; then
        eval "$(python3 -c "
import json, sys
try:
    with open('$CONFIG_FILE') as f:
        c = json.load(f)
    if not isinstance(c, dict):
        sys.exit(1)
    print('HUB_URL=' + repr(c.get('hub', '')))
    print('PROJECT=' + repr(c.get('project', '')))
    print('TEAM=' + repr(c.get('team', 'ungrouped')))
    print('PLATFORM=' + repr(c.get('platform', 'unknown')))
except:
    sys.exit(1)
" 2>/dev/null)" || return 1
    else
        return 1
    fi

    # Apply defaults for empty values
    PROJECT="\${PROJECT:-$(basename "$(pwd)")}"
    TEAM="\${TEAM:-ungrouped}"
    PLATFORM="\${PLATFORM:-unknown}"
    return 0
}

# Read config — exit silently if unavailable
if ! read_config; then
    exit 0
fi

# Validate hub URL is HTTPS
if [[ -z "$HUB_URL" ]]; then
    exit 0
fi
if [[ "$HUB_URL" != https://* ]]; then
    echo "[ai-gov] WARNING: Hub URL is not HTTPS — skipping telemetry transmission." >&2
    exit 0
fi

# --- Hash developer email ---
DEV_EMAIL=$(git config user.email 2>/dev/null || echo "")
if [[ -z "$DEV_EMAIL" ]]; then
    DEVELOPER_HASH="unknown0000000000000000000000000000000000000000000000000000000000"
elif command -v sha256sum &>/dev/null; then
    DEVELOPER_HASH=$(printf '%s' "$DEV_EMAIL" | sha256sum | cut -d' ' -f1)
elif command -v shasum &>/dev/null; then
    DEVELOPER_HASH=$(printf '%s' "$DEV_EMAIL" | shasum -a 256 | cut -d' ' -f1)
else
    DEVELOPER_HASH="unknown0000000000000000000000000000000000000000000000000000000000"
fi

# --- Calculate compliance_pct from precommit.log ---
COMPLIANCE_PCT=100
VIOLATIONS="[]"

if [[ -f "$LOG_FILE" ]]; then
    LAST_ENTRIES=$(tail -20 "$LOG_FILE" 2>/dev/null || echo "")
    if [[ -n "$LAST_ENTRIES" ]]; then
        TOTAL_COUNT=$(echo "$LAST_ENTRIES" | wc -l | tr -d ' ')
        PASS_COUNT=$(echo "$LAST_ENTRIES" | grep -c '|pass|' || echo "0")
        if [[ "$TOTAL_COUNT" -gt 0 ]]; then
            COMPLIANCE_PCT=$(( (PASS_COUNT * 100) / TOTAL_COUNT ))
        fi
        # Extract unique violation types from fail entries (not included — violations are empty for pre-push)
    fi
fi

# --- Collect AI usage data from precommit.log ---
AI_ASSISTED_COUNT=0
AI_COMMANDS_USED=""
HAS_CLAUDE=false
HAS_KIRO=false

if [[ -f "$LOG_FILE" ]]; then
    AI_ENTRIES=$(tail -20 "$LOG_FILE" 2>/dev/null || echo "")
    if [[ -n "$AI_ENTRIES" ]]; then
        while IFS= read -r line; do
            # Parse pipe-delimited fields: timestamp|status|ai_platform|command
            AI_PLAT=$(echo "$line" | cut -d'|' -f3 2>/dev/null || echo "")
            AI_CMD=$(echo "$line" | cut -d'|' -f4 2>/dev/null || echo "")

            # Backward compatibility: treat missing/empty platform as "manual"
            if [[ -z "$AI_PLAT" ]]; then
                AI_PLAT="manual"
            fi

            # Count AI-assisted entries (platform != "manual")
            if [[ "$AI_PLAT" != "manual" ]]; then
                AI_ASSISTED_COUNT=$((AI_ASSISTED_COUNT + 1))

                # Track which platforms are present
                if [[ "$AI_PLAT" == "claude-code" ]]; then
                    HAS_CLAUDE=true
                elif [[ "$AI_PLAT" == "kiro" ]]; then
                    HAS_KIRO=true
                fi

                # Collect distinct command names (non-empty only)
                if [[ -n "$AI_CMD" ]]; then
                    if [[ -z "$AI_COMMANDS_USED" ]]; then
                        AI_COMMANDS_USED="$AI_CMD"
                    elif ! echo "$AI_COMMANDS_USED" | grep -qF "$AI_CMD"; then
                        AI_COMMANDS_USED="$AI_COMMANDS_USED,$AI_CMD"
                    fi
                fi
            fi
        done <<< "$AI_ENTRIES"
    fi
fi

# Determine primary AI platform
if [[ "$HAS_CLAUDE" == true && "$HAS_KIRO" == true ]]; then
    AI_PLATFORM="mixed"
elif [[ "$HAS_CLAUDE" == true ]]; then
    AI_PLATFORM="claude-code"
elif [[ "$HAS_KIRO" == true ]]; then
    AI_PLATFORM="kiro"
else
    AI_PLATFORM="manual"
fi

# Determine ai_assisted boolean
if [[ "$AI_ASSISTED_COUNT" -gt 0 ]]; then
    AI_ASSISTED=true
else
    AI_ASSISTED=false
fi

# Build commands_used JSON array from comma-separated list
COMMANDS_JSON="[]"
if [[ -n "$AI_COMMANDS_USED" ]]; then
    COMMANDS_JSON="["
    FIRST=true
    IFS=',' read -ra CMD_ARRAY <<< "$AI_COMMANDS_USED"
    for cmd in "\${CMD_ARRAY[@]}"; do
        if [[ "$FIRST" == true ]]; then
            COMMANDS_JSON="\${COMMANDS_JSON}\\"$cmd\\""
            FIRST=false
        else
            COMMANDS_JSON="\${COMMANDS_JSON},\\"$cmd\\""
        fi
    done
    COMMANDS_JSON="\${COMMANDS_JSON}]"
fi

# --- Count active AI agent hooks ---
ACTIVE_HOOKS_COUNT=0

# Count .js files in .claude/hooks/ (Claude Code agent hooks)
if [[ -d ".claude/hooks" ]]; then
    CLAUDE_HOOKS=$(find .claude/hooks -maxdepth 1 -name "*.js" -type f 2>/dev/null | wc -l | tr -d ' ') || CLAUDE_HOOKS=0
    ACTIVE_HOOKS_COUNT=$((ACTIVE_HOOKS_COUNT + CLAUDE_HOOKS))
fi

# Count .kiro.hook files in .kiro/hooks/ (Kiro hooks)
if [[ -d ".kiro/hooks" ]]; then
    KIRO_HOOKS=$(find .kiro/hooks -maxdepth 1 -name "*.kiro.hook" -type f 2>/dev/null | wc -l | tr -d ' ') || KIRO_HOOKS=0
    ACTIVE_HOOKS_COUNT=$((ACTIVE_HOOKS_COUNT + KIRO_HOOKS))
fi

# --- Process refs from stdin ---
ZERO="0000000000000000000000000000000000000000"
TOTAL_COMMITS=0
BRANCH=""

while read -r LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA; do
    # Skip delete pushes
    if [[ "$LOCAL_SHA" == "$ZERO" ]]; then
        continue
    fi

    # Extract branch name from ref
    BRANCH="\${LOCAL_REF#refs/heads/}"

    # Count commits
    if [[ "$REMOTE_SHA" == "$ZERO" ]]; then
        # New branch — count reachable commits, cap at 50
        COUNT=$(git rev-list --count --max-count=50 "$LOCAL_SHA" 2>/dev/null || echo "1")
    else
        COUNT=$(git rev-list --count "$REMOTE_SHA..$LOCAL_SHA" 2>/dev/null || echo "1")
    fi

    TOTAL_COMMITS=$((TOTAL_COMMITS + COUNT))
done

# Cap total commits at 50
if [[ "$TOTAL_COMMITS" -gt 50 ]]; then
    TOTAL_COMMITS=50
fi

# If no commits to report, exit
if [[ "$TOTAL_COMMITS" -eq 0 ]]; then
    exit 0
fi

# --- Compute dedup_key ---
PUSH_TS=$(date +%s)
WINDOW=$((PUSH_TS / 300))
DEDUP_INPUT="\${PROJECT}\${DEVELOPER_HASH}\${BRANCH}\${WINDOW}"

if command -v sha256sum &>/dev/null; then
    DEDUP_KEY=$(printf '%s' "$DEDUP_INPUT" | sha256sum | cut -d' ' -f1)
elif command -v shasum &>/dev/null; then
    DEDUP_KEY=$(printf '%s' "$DEDUP_INPUT" | shasum -a 256 | cut -d' ' -f1)
else
    DEDUP_KEY="unknown0000000000000000000000000000000000000000000000000000000000"
fi

# --- Build and send payload ---
PAYLOAD=$(cat <<EOJSON
{
  "project": "$PROJECT",
  "team": "$TEAM",
  "platform": "$PLATFORM",
  "developer_hash": "$DEVELOPER_HASH",
  "hook_version": "$HOOK_VERSION",
  "commit_count": $TOTAL_COMMITS,
  "compliance_pct": $COMPLIANCE_PCT,
  "bypass": false,
  "violations": $VIOLATIONS,
  "branch": "$BRANCH",
  "push_ts": $PUSH_TS,
  "dedup_key": "$DEDUP_KEY",
  "ai_usage": {
    "ai_assisted": $AI_ASSISTED,
    "ai_assisted_count": $AI_ASSISTED_COUNT,
    "commands_used": $COMMANDS_JSON,
    "ai_platform": "$AI_PLATFORM",
    "active_hooks_count": $ACTIVE_HOOKS_COUNT
  }
}
EOJSON
)

# Send in background — never block the push
(curl -s -X POST \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer \${AI_GOV_SECRET:-}" \\
    --max-time 5 \\
    --connect-timeout 3 \\
    -d "$PAYLOAD" \\
    "\${HUB_URL}/api/events" >/dev/null 2>&1 || true) &

# Always exit 0 — never block a push
exit 0
`;
}
