export function generateWorkspacePreCommit(agent: 'claude-code' | 'kiro' = 'claude-code'): string {
    const agentDir = agent === 'kiro' ? '.kiro' : '.claude';
    return `#!/usr/bin/env bash
# Generated by ai-gov v17.1.0 — Workspace pre-commit hook
# Groups staged files by project, runs per-project checks, reports grouped results.
# Falls back to single-project mode if no ${agentDir}/steering/project-registry.md found.

set -euo pipefail

# Dependencies: git, sed, grep, wc — all standard POSIX tools, no external install needed.

# Skip during merge / rebase
[[ -f ".git/MERGE_HEAD" ]] && exit 0
[[ -d ".git/rebase-merge" || -d ".git/rebase-apply" ]] && exit 0

# Get staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACMR 2>/dev/null || true)
[[ -z "$STAGED" ]] && exit 0

REGISTRY="${agentDir}/steering/project-registry.md"

echo ""
echo "  🔒 Pre-commit governance check (workspace)"
echo "  ────────────────────────────────────────────"

ERRORS=0
WARNINGS=0

# ── Workspace mode ────────────────────────────────────────────────────────────

if [[ -f "$REGISTRY" ]]; then

    # Parse project paths and stacks from registry table.
    # Registry lines look like: | \`backend/api-server\` | nodejs | backend | _describe_ |
    declare -a PROJ_PATHS=()
    declare -A PROJ_STACK=()

    while IFS= read -r line; do
        if echo "$line" | grep -qE '^\\| \`[^\`]+\` \\| [a-z]+ \\|'; then
            proj_path=$(echo "$line" | sed 's/^| \`\\([^\`]*\\)\` .*/\\1/')
            proj_stack=$(echo "$line" | sed 's/^| \`[^\`]*\` | \\([a-z]*\\) .*/\\1/')
            PROJ_PATHS+=("$proj_path")
            PROJ_STACK["$proj_path"]="$proj_stack"
        fi
    done < "$REGISTRY"

    UNMATCHED_FILES=""

    for proj_path in "\${PROJ_PATHS[@]+""\${PROJ_PATHS[@]}""}"; do
        proj_stack="\${PROJ_STACK[$proj_path]}"
        proj_files=$(echo "$STAGED" | grep "^$\{proj_path}/" || true)
        [[ -z "$proj_files" ]] && continue

        proj_errors=0
        proj_warnings=0
        proj_output=""

        echo ""
        echo "  $\{proj_path}/ ($\{proj_stack}):"

        # ── File-size check ───────────────────────────────────────────────────
        # Frontend stacks enforce 300-line limit; backend/java stacks are exempt.
        case "$proj_stack" in
            react|angular|flutter)
                while IFS= read -r f; do
                    [[ -z "$f" || ! -f "$f" ]] && continue
                    lines=$(wc -l < "$f" 2>/dev/null || echo 0)
                    if [[ $lines -gt 300 ]]; then
                        proj_output="$\{proj_output}\\n    ❌ FILE SIZE: $f has $lines lines (max 300 for $\{proj_stack})"
                        proj_errors=$((proj_errors + 1))
                    fi
                done <<< "$proj_files"
                ;;
        esac

        # ── Secrets check (all stacks) ────────────────────────────────────────
        while IFS= read -r f; do
            [[ -z "$f" || ! -f "$f" ]] && continue
            # Skip test/fixture files
            echo "$f" | grep -qiE '(test|spec|mock|fixture|\\.example|\\.template)' && continue
            if grep -qiE '(AKIA[0-9A-Z]{16}|sk-[a-zA-Z0-9]{20,}|["'"'"']password["'"'"']\\s*[:=]\\s*["'"'"'][^"'"'"']{4,}|-----BEGIN (RSA |EC )?PRIVATE KEY)' "$f" 2>/dev/null; then
                proj_output="$\{proj_output}\\n    ❌ SECRETS: credentials detected in $f"
                proj_errors=$((proj_errors + 1))
            fi
        done <<< "$proj_files"

        # ── No-todos check (all stacks) ───────────────────────────────────────
        while IFS= read -r f; do
            [[ -z "$f" || ! -f "$f" ]] && continue
            todo_line=$(grep -n "TODO\\|FIXME\\|HACK\\|XXX" "$f" 2>/dev/null | head -1 || true)
            if [[ -n "$todo_line" ]]; then
                proj_output="$\{proj_output}\\n    ⚠️  TODO: $f — $todo_line"
                proj_warnings=$((proj_warnings + 1))
            fi
        done <<< "$proj_files"

        # ── Output per-project results ────────────────────────────────────────
        if [[ $proj_errors -eq 0 && $proj_warnings -eq 0 ]]; then
            echo "    ✅ All checks passed"
        else
            [[ -n "$proj_output" ]] && echo -e "$proj_output"
        fi

        ERRORS=$((ERRORS + proj_errors))
        WARNINGS=$((WARNINGS + proj_warnings))
    done

    # Report staged files that do not belong to any known project
    for f in $STAGED; do
        matched=0
        for proj_path in "\${PROJ_PATHS[@]+""\${PROJ_PATHS[@]}""}"; do
            if echo "$f" | grep -q "^$\{proj_path}/"; then
                matched=1
                break
            fi
        done
        if [[ $matched -eq 0 ]]; then
            UNMATCHED_FILES="$\{UNMATCHED_FILES} $f"
        fi
    done

    if [[ -n "$UNMATCHED_FILES" ]]; then
        echo ""
        echo "  workspace-root files (not in any project):"
        for f in $UNMATCHED_FILES; do
            echo "    • $f"
        done
    fi

else
    # ── Fallback: single-project mode ─────────────────────────────────────────
    echo "  ℹ️  No project-registry.md found — falling back to single-project mode."
    HOOKS_DIR="$(cd "$(dirname "$0")/../.." && pwd)/${agentDir}/git-hooks"
    if [[ -f "$HOOKS_DIR/pre-commit.sh" ]]; then
        bash "$HOOKS_DIR/pre-commit.sh"
        exit $?
    fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
if [[ $ERRORS -gt 0 ]]; then
    echo "  ❌ $ERRORS blocking issue(s). Fix and try again."
    echo "  (bypass with: git commit --no-verify)"
    exit 1
elif [[ $WARNINGS -gt 0 ]]; then
    echo "  ⚠️  $WARNINGS warning(s). Commit allowed — consider fixing."
    exit 0
else
    echo "  ✅ All checks passed."
    exit 0
fi
`;
}
