import type { CheckResult } from '../types.js';

const STATUS_EMOJI: Record<string, string> = {
    pass: '✅',
    fail: '❌',
    warn: '⚠️',
    skip: '⏭️',
};

export function formatGitlab(results: CheckResult[], changedFiles: string[]): string {
    const lines: string[] = [];
    const blockers = results.filter(r => r.status === 'fail').length;
    const warnings = results.filter(r => r.status === 'warn').length;

    lines.push('## 🏛️ Governance MR Review');
    lines.push('');
    lines.push(`**Changed files:** ${changedFiles.length} | **Blockers:** ${blockers} | **Warnings:** ${warnings}`);
    lines.push('');

    if (blockers > 0) {
        lines.push('> ❌ **This MR has blocking issues that must be resolved before merge.**');
    } else if (warnings > 0) {
        lines.push('> ⚠️ **This MR has warnings. Merge is allowed but consider addressing them.**');
    } else {
        lines.push('> ✅ **All governance checks passed.**');
    }
    lines.push('');

    for (const result of results) {
        const icon = STATUS_EMOJI[result.status] ?? '';
        lines.push(`### ${icon} ${result.name}`);
        lines.push(`${result.details}`);

        if (result.items.length > 0) {
            lines.push('');
            for (const item of result.items) {
                lines.push(`- \`${item.file}\`: ${item.message}`);
            }
        }
        lines.push('');
    }

    lines.push('---');
    lines.push('*Generated by [ai-gov](https://github.com/jvvsrinukumar/ai-gov-cli)*');

    return lines.join('\n');
}
